### PR TITLE
migrate to vite

### PR DESCRIPTION
**Pull request by sk337**
Migrate RDD over to vote for typescript and general qol

### CODE REVIEW

**Comment by sk337** [comment]
tested and binaries do extract and function as intended could have re made this but decided to keep as much of base code as possible

**Comment by regginator** [comment]
Thanks for the PR!

Sorry, we're not planning to add any extra build steps or web frameworks to RDD, as to keep the project as minimal as possible... It is necessary for `index.html` to be able to run directly off of the filesystem with no build/serve steps. However, I do still plan on a slight redesign and complete refactor of `rdd.js` to use `fetch` instead of XMLHttpRequest eventually.

**Comment by sk337** [comment]
?? this is serverless once it is built and you can use gh actions to build or cf pages

**Comment by regginator** [comment]
> ?? this is serverless once it is built and you can use gh actions to build or cf pages

I am aware,

> we're not planning to add any extra build steps or web frameworks to RDD, as to keep the project as minimal as possible

> It is necessary for `index.html` to be able to run directly off of the filesystem with no build/serve steps

**Comment by sk337** [comment]
> > ?? this is serverless once it is built and you can use gh actions to build or cf pages
> 
> I am aware,
> 
> > we're not planning to add any extra build steps or web frameworks to RDD, as to keep the project as minimal as possible
> 
> > It is necessary for `index.html` to be able to run directly off of the filesystem with no build/serve steps

ok

**Pull request closed without merging**
